import java.util.*;
import java.lang.*;
import java.io.*;

public class Main {
    public static void main(String[] args) throws java.lang.Exception {
        Scanner scanner = new Scanner(System.in);

        // Declare two different variables
        int num1 = scanner.nextInt();
        int num2 = scanner.nextInt();

        // Print the input values
        System.out.println("num1: " + num1);
        System.out.println("num2: " + num2);

        scanner.close(); // Close the scanner
    }
}
